<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div class="EXPLORE-THE-WORLD-OF">
		<h3>EXPLORE THE WORLD OF COMPOUND MICROSCOPES</h3>
	</div>
	<div class="Taking-design">
		<p>Taking design cues from the popular M10L Series, the non-digital M10 compound microscope series expands your options. Ideal for higher education and professional applications</p>
	</div>
	
	<div class="View-Products">
	
		<h5>SHOP PRODUCTS<div class="a"/></h5>
		
	</div>
	
	
	
	
	
	<div class="Related-Product-Carousel">
		<div class="Rectangle"></div>
		<div class="Rectangle"></div>
		<div class="Rectangle"></div>
		<div class="Rectangle"></div>
	</div>
</body>
</html>
